[package]
name = "webrs"
version = "0.1.0"
authors = ["Aleksey Kuznetsov <zummenix@gmail.com>"]

[dependencies]
iron = "0.2.5"
router = "0.0.16"
urlencoded = "0.2.0"
serde_json = "0.6.0"
postgres = "0.10.2"
